"""Compile the Platinum icon set (assets/icons/platinum-icons.picon) into C.

usage: build_icons.py [--specimen OUT.png | --check]

Writes lib/icons_data.h: each icon as rows of palette characters plus the
palette, decoded by lib/icons.c. --specimen renders every icon at 1x and
4x (unselected and selected) on white, gray and the desktop color.
"""
import os
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "assets", "icons", "platinum-icons.picon")
OUT = os.path.join(ROOT, "lib", "icons_data.h")
# Icons lib/icons.c expects, in enum pl_icon_kind order.
KINDS = ["folder", "document", "application", "disk", "trash-empty", "trash-full", "caution",
         "disk-image", "classic", "shared-folder", "system-folder", "control-panels"]


def parse():
    palette, icons, cur = {".": None}, {}, None
    with open(SRC, encoding="utf-8") as f:
        for n, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            if not line.strip() or line.startswith(";"):
                continue
            words = line.split()
            if words[0] == "color" and len(words) == 3:
                palette[words[1]] = int(words[2], 16)
                cur = None
            elif words[0] == "icon" and len(words) == 3:
                cur = (words[1], int(words[2]))
                if cur in icons:
                    sys.exit(f"{SRC}:{n}: {cur} defined twice")
                icons[cur] = []
            elif cur:
                for c in line:
                    if c not in palette:
                        sys.exit(f"{SRC}:{n}: {c!r} isn't in the palette")
                icons[cur].append(line)
            else:
                sys.exit(f"{SRC}:{n}: unexpected line")
    for (name, size), rows in icons.items():
        if len(rows) != size or any(len(r) != size for r in rows):
            sys.exit(f"{SRC}: icon {name} {size} must be {size} rows of {size}")
    for k in KINDS:
        for s in (32, 16):
            if (k, s) not in icons:
                sys.exit(f"{SRC}: missing icon {k} {s}")
    return palette, icons


def emit(palette, icons, out):
    lines = [
        "/* Generated by tools/icons/build_icons.py from assets/icons/platinum-icons.picon.",
        " * Do not edit; edit the .picon source and regenerate. */",
        "",
        "/* Palette: ARGB for each pixel character ('.' is transparent). */",
        "static uint32_t icon_color(char c) {",
        "\tswitch (c) {",
    ]
    for c, v in sorted(palette.items(), key=lambda kv: kv[0]):
        if v is not None:
            lines.append(f"\tcase '{c}': return 0xFF{v:06X};")
    lines += ["\tdefault: return 0;", "\t}", "}", ""]
    for k in KINDS:
        for s in (32, 16):
            ident = f"icon_{k.replace('-', '_')}_{s}"
            lines.append(f"static const char *const {ident}[{s}] = {{")
            lines += [f'\t"{r}",' for r in icons[(k, s)]]
            lines.append("};")
    lines.append("")
    lines.append("/* By enum pl_icon_kind: the 32 and 16 px versions. */")
    lines.append("static const char *const *const icon_rows[][2] = {")
    for k in KINDS:
        ident = f"icon_{k.replace('-', '_')}"
        lines.append(f"\t{{ {ident}_32, {ident}_16 }},")
    lines.append("};")
    lines.append("")
    with open(out, "w") as f:
        f.write("\n".join(lines))


def specimen(palette, icons, out):
    from PIL import Image
    backgrounds = [(255, 255, 255), (0xDD, 0xDD, 0xDD), (0x66, 0x66, 0xCC)]
    cell = 36
    w = 8 + len(KINDS) * cell
    h = 8 + len(backgrounds) * 2 * cell
    img = Image.new("RGB", (w, h), (255, 255, 255))
    px = img.load()
    for bi, bg in enumerate(backgrounds):
        for sel in (False, True):
            y0 = 4 + (bi * 2 + sel) * cell
            for x in range(w):
                for y in range(y0 - 2, y0 + cell - 2):
                    px[x, y] = bg
            for ki, k in enumerate(KINDS):
                for s, dx in ((32, 0), (16, 0)):
                    rows = icons[(k, s)]
                    ox = 4 + ki * cell + (0 if s == 32 else 0)
                    oy = y0 if s == 32 else y0
                    if s == 16:
                        continue
                    for j, r in enumerate(rows):
                        for i, c in enumerate(r):
                            v = palette[c]
                            if v is None:
                                continue
                            rgb = ((v >> 16) & 255, (v >> 8) & 255, v & 255)
                            if sel:
                                rgb = tuple(ch // 2 for ch in rgb)
                            px[ox + i, oy + j] = rgb
    big = img.resize((w * 4, h * 4), Image.NEAREST)
    # The 16 px icons, alongside at 4x.
    small = Image.new("RGB", (8 + len(KINDS) * 20, 24), (0xDD, 0xDD, 0xDD))
    sp = small.load()
    for ki, k in enumerate(KINDS):
        for j, r in enumerate(icons[(k, 16)]):
            for i, c in enumerate(r):
                v = palette[c]
                if v is not None:
                    sp[4 + ki * 20 + i, 4 + j] = ((v >> 16) & 255, (v >> 8) & 255, v & 255)
    small = small.resize((small.width * 4, small.height * 4), Image.NEAREST)
    sheet = Image.new("RGB", (max(big.width, small.width), big.height + small.height + 8), "white")
    sheet.paste(big, (0, 0))
    sheet.paste(small, (0, big.height + 8))
    sheet.save(out)


def main():
    palette, icons = parse()
    if sys.argv[1:] == ["--check"]:
        import tempfile
        with tempfile.NamedTemporaryFile("r", suffix=".h") as tmp:
            emit(palette, icons, tmp.name)
            with open(OUT) as f:
                if f.read() != tmp.read():
                    sys.exit("lib/icons_data.h is out of date: run tools/icons/build_icons.py")
        return
    emit(palette, icons, OUT)
    print(f"{len(icons)} icons")
    if len(sys.argv) == 3 and sys.argv[1] == "--specimen":
        specimen(palette, icons, sys.argv[2])


if __name__ == "__main__":
    main()
