"""Generate lib/buttons_data.h: 9-slice push-button art measured from
HIG figure 3-2 (img-059-088: "Cancel" default button with ring, "OK"
standard button) and figure 2-3 (img-023-006: pressed default button,
whose figure is stretched vertically; duplicate rows are dropped).

Each slice table holds the left columns, one stretchable middle column and
the right columns of every row, as hex gray digits.
"""
import os
import sys

from PIL import Image

FIGS = os.path.join(os.path.dirname(__file__), "figs")


def grays(name, x0, y0, w, h, drop_rows=()):
    im = Image.open(os.path.join(FIGS, name + ".png")).convert("RGB")
    rows = []
    for y in range(y0, y0 + h):
        if y in drop_rows:
            continue
        row = ""
        for x in range(x0, x0 + w):
            r, g, b = im.getpixel((x, y))
            assert r == g == b and r % 0x11 == 0, (name, x, y, (r, g, b))
            row += "%x" % (r // 0x11)
        rows.append(row)
    return rows


def clear_corners(rows, bg="d", reach=4):
    """Background showing outside the rounded corners becomes '.'."""
    grid = [list(r) for r in rows]
    h, w = len(grid), len(grid[0])
    for cx, cy, dx, dy in ((0, 0, 1, 1), (w - 1, 0, -1, 1),
                           (0, h - 1, 1, -1), (w - 1, h - 1, -1, -1)):
        stack = [(cx, cy)]
        while stack:
            x, y = stack.pop()
            if not (0 <= x < w and 0 <= y < h) or grid[y][x] != bg:
                continue
            if abs(x - cx) >= reach or abs(y - cy) >= reach:
                continue
            grid[y][x] = "."
            stack += [(x + dx, y), (x, y + dy)]
    return ["".join(r) for r in grid]


def sliced(rows, left, right, mid, bg="d"):
    rows = clear_corners(rows, bg)
    return [r[:left] + r[mid] + r[len(r) - right:] for r in rows]


def emit(out, name, rows, left, right, comment):
    out.append(f"/* {comment} */")
    out.append(f"static const struct nine_slice {name} = {{")
    out.append(f"\t.left = {left}, .right = {right}, .height = {len(rows)},")
    out.append("\t.rows = {")
    for r in rows:
        out.append(f'\t\t"{r}",')
    out.append("\t},")
    out.append("};")
    out.append("")


def main():
    out = [
        "/* Generated by tools/measure/gen_buttons.py from Apple's Mac OS 8 HIG",
        " * figures; do not edit. Hex digit = gray level. */",
        "",
    ]
    # Standard button "OK": 60x20 at (223,161). Stretch column 10.
    std = grays("img-059-088", 223, 161, 60, 20)
    emit(out, "button_standard", sliced(std, 8, 8, 10), 8, 8,
         "standard push button, HIG fig 3-2")

    # Default button with its ring, "Cancel": 66x26 at (220,125). Stretch column 9 (column 13 holds the label).
    dflt = grays("img-059-088", 220, 125, 66, 26)
    emit(out, "button_default", sliced(dflt, 11, 11, 9), 11, 11,
         "default push button with ring, HIG fig 3-2")

    # Pressed default, fig 2-3: 59x29 at (1,1); rows 5, 9 and 26 duplicate
    # their neighbours (the figure is stretched to 110%).
    pressed = grays("img-023-006", 1, 1, 59, 29, drop_rows=(5, 9, 26))
    assert len(pressed) == 26, len(pressed)
    emit(out, "button_default_pressed", sliced(pressed, 11, 11, 9, bg="f"), 11, 11,
         "pressed default push button with ring, HIG fig 2-3 (de-stretched)")

    # Pressed standard: the pressed default without its ring; the pixels
    # the ring showed through the rounded corners become background.
    inner = [r[3:-3] for r in pressed[3:-3]]
    bg = "d"
    corners = [(1, 0), (0, 1), (len(inner[0]) - 2, 0), (len(inner[0]) - 1, 1),
               (0, len(inner) - 2), (1, len(inner) - 1),
               (len(inner[0]) - 1, len(inner) - 2), (len(inner[0]) - 2, len(inner) - 1),
               (0, 0), (len(inner[0]) - 1, 0), (0, len(inner) - 1),
               (len(inner[0]) - 1, len(inner) - 1)]
    inner = [list(r) for r in inner]
    for x, y in corners:
        inner[y][x] = bg
    inner = ["".join(r) for r in inner]
    emit(out, "button_standard_pressed", sliced(inner, 8, 8, 10), 8, 8,
         "pressed standard push button (derived from fig 2-3)")

    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(__file__), "..", "..", "lib", "buttons_data.h")
    with open(path, "w") as f:
        f.write("\n".join(out))
    print("wrote", path)


main()
