#ifndef PLATINUM_PATTERNS_H
#define PLATINUM_PATTERNS_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Desktop patterns: Platinum 2026's own tiles, generated by
 * tools/patterns/make_patterns.py. Index 0 is the default.
 */

#include "draw.h"

int pl_pattern_count(void);
const char *pl_pattern_id(int index);   /* "ocean-ripple" */
const char *pl_pattern_name(int index); /* "Ocean Ripple" */
/* Index of the pattern with this id, or 0 (the default) if none. */
int pl_pattern_find(const char *id);
/* Tile the pattern over canvas pixels x0..x1, y0..y1 (inclusive),
 * aligned to the canvas origin so neighbouring fills line up. */
void pl_pattern_fill(struct pl_canvas *c, int index, int x0, int y0, int x1, int y1);

#ifdef __cplusplus
}
#endif

#endif
