install_data('zacos9-install',
  install_dir: get_option('libexecdir') / 'zacos9', install_mode: 'rwxr-xr-x')
install_data('org.zacos9.installer.policy',
  install_dir: get_option('datadir') / 'polkit-1' / 'actions')
install_data('50-zacos9-installer.rules',
  install_dir: get_option('datadir') / 'polkit-1' / 'rules.d')
